spring:
  application:
    name: transmitter
  datasource:
    url: jdbc:postgresql://localhost:5431/transmitter
    username: root
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
  flyway:
    enabled: true
    placeholder-replacement: false
    baseline-on-migrate: true
    validate-on-migrate: true
  threads:
    virtual:
      enabled: true

management:
  metrics:
    enable:
      all: true
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

otel:
  traces:
    exporter: otlp
    sampler: parentbased_always_on
  metrics:
    exporter: otlp
  exporter:
    otlp:
      endpoint: http://localhost:4317
      protocol: grpc
  instrumentation:
    micrometer:
      enabled: true
