receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ":4317"
#      http:
#        endpoint: ":4318"
#        cors:
#          allowed_origins:

exporters:
  otlp/elastic:
    endpoint: "apm-server:8200"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9464"
  debug:
    verbosity: detailed

processors:
  batch:
    send_batch_size: 10
    timeout: 1s

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [ otlp ]
      exporters: [ otlp/elastic]
    metrics:
      receivers: [ otlp ]
      exporters: [ prometheus,  otlp/elastic, debug]


